version: '3.4'

services:
  auth-server:
    image: allen8673/auth-server
    container_name: auth-server
    # build: .
    environment:
      NODE_ENV: production
      PORT: 3030
    ports:
      - 3030:3030